#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_TOOLBAR                             117
#define IDR_MAINFRAME                           122
#define IDR_POPUPMENU                           123
#define IDD_ABOUT                               126
#define IDD_PARAMETER                           129
#define IDI_APP                                 130
#define IDI_VIEW                                135
#define IDI_SCOPE                               136
#define IDI_EDITOR                              138
#define IDR_EDITOR                              141
#define IDC_MAKEFUNC                            40000
#define IDC_MAKESUBSYS                          40001
#define IDC_MAKEINPUT                           40002
#define IDC_MAKEOUTPUT                          40003
#define IDC_COMPILE                             40004
#define IDC_GENERATE                            40005
#define IDC_STARTSIM                            40006
#define IDC_BLKEDIT                             40007
#define IDC_HOMEPAGE                            40008
#define IDC_ARRANGE                             40009
#define IDC_LOADBLK                             40010
#define IDC_SAVEBLK                             40011
#define IDC_QQTALK                              40012
#define IDC_NODDELETE                           40014
#define IDC_MAKETEXT                            40015
#define IDC_MAKELINK                            40016
#define IDC_LNKEXTEND                           40017
#define IDC_STOPSIM                             40018
#define IDC_BLKEXPLORER                         40019
#define IDC_NEW                                 40020
#define IDC_OPEN                                40021
#define IDC_SAVE                                40022
#define IDC_SAVEAS                              40023
#define IDC_EXIT                                40024
#define IDC_CUT                                 40025
#define IDC_COPY                                40026
#define IDC_PASTE                               40027
#define IDC_DELETE                              40028
#define IDC_VTILE                               40030
#define IDC_HTILE                               40031
#define IDC_CASCADE                             40032
#define IDC_MESSAGE                             40033
#define IDC_ABOUT                               40034
#define IDC_PARAMETER                           40035
#define IDB_LIMIT                               40036
#define IDB_ALGO                                40037
#define IDB_SLEEP                               40038
#define IDB_STEP                                40039
#define IDB_CURRENT                             40040
#define IDB_CYCLE                               40041
#define IDB_DURATION                            40042
#define IDC_PRINT                               40043
